function TT=fkine_mine(q)
for ii=1:6
    eval(['th_' num2str(ii) '=q(' num2str(ii) ');']);
end

TT=[
[ - cos(th_6)*(sin(th_4)*(cos(th_3)*sin(th_1) + cos(th_1)*sin(th_2)*sin(th_3)) - cos(th_1)*cos(th_2)*cos(th_4)) - sin(th_6)*(sin(th_5)*(cos(th_4)*(cos(th_3)*sin(th_1) + cos(th_1)*sin(th_2)*sin(th_3)) + cos(th_1)*cos(th_2)*sin(th_4)) + cos(th_5)*(sin(th_1)*sin(th_3) - cos(th_1)*cos(th_3)*sin(th_2))), sin(th_6)*(sin(th_4)*(cos(th_3)*sin(th_1) + cos(th_1)*sin(th_2)*sin(th_3)) - cos(th_1)*cos(th_2)*cos(th_4)) - cos(th_6)*(sin(th_5)*(cos(th_4)*(cos(th_3)*sin(th_1) + cos(th_1)*sin(th_2)*sin(th_3)) + cos(th_1)*cos(th_2)*sin(th_4)) + cos(th_5)*(sin(th_1)*sin(th_3) - cos(th_1)*cos(th_3)*sin(th_2))), sin(th_5)*(sin(th_1)*sin(th_3) - cos(th_1)*cos(th_3)*sin(th_2)) - cos(th_5)*(cos(th_4)*(cos(th_3)*sin(th_1) + cos(th_1)*sin(th_2)*sin(th_3)) + cos(th_1)*cos(th_2)*sin(th_4)), cos(th_1)/5 + cos(th_1)*cos(th_2) - (cos(th_6)*(sin(th_4)*(cos(th_3)*sin(th_1) + cos(th_1)*sin(th_2)*sin(th_3)) - cos(th_1)*cos(th_2)*cos(th_4)))/2 - (sin(th_6)*(sin(th_5)*(cos(th_4)*(cos(th_3)*sin(th_1) + cos(th_1)*sin(th_2)*sin(th_3)) + cos(th_1)*cos(th_2)*sin(th_4)) + cos(th_5)*(sin(th_1)*sin(th_3) - cos(th_1)*cos(th_3)*sin(th_2))))/2 - sin(th_4)*(cos(th_3)*sin(th_1) + cos(th_1)*sin(th_2)*sin(th_3)) + cos(th_1)*cos(th_2)*cos(th_4)];
[   cos(th_6)*(sin(th_4)*(cos(th_1)*cos(th_3) - sin(th_1)*sin(th_2)*sin(th_3)) + cos(th_2)*cos(th_4)*sin(th_1)) + sin(th_6)*(sin(th_5)*(cos(th_4)*(cos(th_1)*cos(th_3) - sin(th_1)*sin(th_2)*sin(th_3)) - cos(th_2)*sin(th_1)*sin(th_4)) + cos(th_5)*(cos(th_1)*sin(th_3) + cos(th_3)*sin(th_1)*sin(th_2))), cos(th_6)*(sin(th_5)*(cos(th_4)*(cos(th_1)*cos(th_3) - sin(th_1)*sin(th_2)*sin(th_3)) - cos(th_2)*sin(th_1)*sin(th_4)) + cos(th_5)*(cos(th_1)*sin(th_3) + cos(th_3)*sin(th_1)*sin(th_2))) - sin(th_6)*(sin(th_4)*(cos(th_1)*cos(th_3) - sin(th_1)*sin(th_2)*sin(th_3)) + cos(th_2)*cos(th_4)*sin(th_1)), cos(th_5)*(cos(th_4)*(cos(th_1)*cos(th_3) - sin(th_1)*sin(th_2)*sin(th_3)) - cos(th_2)*sin(th_1)*sin(th_4)) - sin(th_5)*(cos(th_1)*sin(th_3) + cos(th_3)*sin(th_1)*sin(th_2)), sin(th_1)/5 + cos(th_2)*sin(th_1) + (cos(th_6)*(sin(th_4)*(cos(th_1)*cos(th_3) - sin(th_1)*sin(th_2)*sin(th_3)) + cos(th_2)*cos(th_4)*sin(th_1)))/2 + sin(th_4)*(cos(th_1)*cos(th_3) - sin(th_1)*sin(th_2)*sin(th_3)) + (sin(th_6)*(sin(th_5)*(cos(th_4)*(cos(th_1)*cos(th_3) - sin(th_1)*sin(th_2)*sin(th_3)) - cos(th_2)*sin(th_1)*sin(th_4)) + cos(th_5)*(cos(th_1)*sin(th_3) + cos(th_3)*sin(th_1)*sin(th_2))))/2 + cos(th_2)*cos(th_4)*sin(th_1)];
[                                                                                                                             cos(th_6)*(cos(th_4)*sin(th_2) + cos(th_2)*sin(th_3)*sin(th_4)) - sin(th_6)*(sin(th_5)*(sin(th_2)*sin(th_4) - cos(th_2)*cos(th_4)*sin(th_3)) + cos(th_2)*cos(th_3)*cos(th_5)),                                                                                                                         - cos(th_6)*(sin(th_5)*(sin(th_2)*sin(th_4) - cos(th_2)*cos(th_4)*sin(th_3)) + cos(th_2)*cos(th_3)*cos(th_5)) - sin(th_6)*(cos(th_4)*sin(th_2) + cos(th_2)*sin(th_3)*sin(th_4)),                                                                               cos(th_2)*cos(th_3)*sin(th_5) - cos(th_5)*(sin(th_2)*sin(th_4) - cos(th_2)*cos(th_4)*sin(th_3)),                                                                                                                                                                                               sin(th_2) + cos(th_4)*sin(th_2) - (sin(th_6)*(sin(th_5)*(sin(th_2)*sin(th_4) - cos(th_2)*cos(th_4)*sin(th_3)) + cos(th_2)*cos(th_3)*cos(th_5)))/2 + (cos(th_6)*(cos(th_4)*sin(th_2) + cos(th_2)*sin(th_3)*sin(th_4)))/2 + cos(th_2)*sin(th_3)*sin(th_4)];
[                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                                                                       0,                                                                                                                                                                             0,                                                                                                                                                                                                                                                                                                                                                                                                                                                     1];
 ];
