clc
clear all

%%
%formulation



%%
%actual data

%a.*q+b=realq
B=[.1 .2 .05 -.1 .3 .15]'+rand(6,1)*.1;
A=[.09 .1 .05 .12 .07 .1]'+rand(6,1).*.02;

L=[.16 .19 .12 .19 .14 .165];


%generate stochastic data in
for ii=1:20
Q{ii}=rand(6,1);
DQ{ii}=rand(6,1)*.01;
q{ii}=(Q{ii}-B)./A+rand(6,1).*1;

xparams=fkine_fun_M26(L,q{ii},A,B);
xparams=xparams(1:3,:);
xparams=xparams+rand(size(xparams)).*.1;

X{ii}=reshape(xparams,12,1);
end


%%
%estimation

x0=[[.1 .1 .1 .1 .1 .1]' [.5 .5 .5 .5 .5 .5]'];

opt = struct(...
    'Algorithm','trust-region-reflective',...
    'DerivativeCheck','off',...
    'Diagnostics','on',...
    'DiffMaxChange',1e-1,...
    'DiffMinChange',1e-17,...
    'Display','iter',...
    'FunValCheck','off',...
    'Jacobian','off',...
    'JacobMult',[],... 
    'JacobPattern','sparse(ones(Jrows,Jcols))',...
    'LargeScale','on',...
    'LevenbergMarquardt','on',...
    'LineSearchType','quadcubic',...
    'MaxFunEvals',[],...
    'MaxIter',400,...
    'MaxPCGIter','max(1,floor(numberOfVariables/2))',...
    'OutputFcn',[],...
    'PlotFcns',[],...
    'PrecondBandWidth',Inf,...
    'ScaleProblem','none',...
    'TolFun',1e-8,...
    'TolPCG',0.1,...
    'TolX',1e-8,...
    'TypicalX','ones(numberOfVariables,1)');


[x,resnorm,~,exitflag,output]=lsqcurvefit(@(x,xdata)fkine_M26_wrapper(x,xdata),x0,[repmat(L',1,numel(q)) ;cell2mat(q)],cell2mat(X),[],[],opt)

[x(:,1)-A x(:,2)-B]
